name: Transunitedfund
favicon: null
layout_spectrum: 0.57863
typography_spectrum: 0.7306460810359567
title: Trans United Fund
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#acabab'
    - '#4c8bc8'
    - '#a73957'
  brandStrength: 1
  lightness: 0.9542897311039269
  saturation: 0.9224453647620976
  rhythmicContrast: 0.004427365260198712
purpose: []
